### ISSUE TITLE
How does the app avoid a Lambda recursive loop detection?

### ISSUE THREAD

**Issue by jeanbmar** [aws-samples/amazon-sqs-dlq-replay-backoff#10]
Hello,

My understanding of the app is that after 16 replay attempts, it will stop working because of the [Lambda recursive loop detection](https://docs.aws.amazon.com/lambda/latest/dg/invocation-recursion.html).

Assuming the Consumer isn't polling, the app has a single chain of requests which does:
SQS -> Consumer Fails -> DLQ -> Lambda -> SQS

Am I right? Do you have any suggestion to handle this?

**Comment by AlexPinhel** [comment]
If the max retries is reached, the Lambda is putting it in SQS and from there, the only way to unblock the message is to look at the SQS queue manually. We didn't put any mechanism on top to avoid recursive loop.
