### ISSUE TITLE
Python 3.7 configured in Cloudformation template is End Of Life

### ISSUE THREAD

**Issue by marcmiro** [aws-samples/amazon-sqs-dlq-replay-backoff#11]
Hello,
When trying to deploy the application with the Cloudformation template it uses runtime python3.7 that is currently in EOL so it is not going to be patched anymore and won't be usable in a couple of months.
Is there the possibility to update it? Should the application be compatible with the version that AWS recommends (3.11)?
Thanks in advance.

**Comment by AlexPinhel** [comment]
Hello, good point. Will update it to 3.11

**Comment by AlexPinhel** [comment]
Template updated to work with 3.11.
No issue during testing.

**Comment by marcmiro** [comment]
Thanks, @AlexPinhel !!
There is this error when trying to deploy the app with the new Semantic Version:
`NotFoundException: Application arn:aws:serverlessrepo:eu-west-1:505173050228:applications/amazon-sqs-dlq-replay-backoff does not have a version 3.0.1`
Is there something more to do to upload it to AWS Public maybe?
Thanks in advance!

**Comment by AlexPinhel** [comment]
oh my bad, I updated by error the semantic version :(

**Comment by marcmiro** [comment]
Thanks @AlexPinhel !!! :)
