### ISSUE TITLE
backoff algorithm uses a wrong variable as the cap

### ISSUE THREAD

**Issue by edank** [aws-samples/amazon-sqs-dlq-replay-backoff#6]
The backoff algorith uses the MESSAGE_RETENTION_PERIOD variable as the cap for the maximum amount of time to delay the message.
Retention period has a maximum of 14 days, while an SQS message has a maximum delay of 15 minutes (900 seconds)

replay.py:
` b = backoff.ExpoBackoffFullJitter(
            base=config.BACKOFF_RATE, 
            cap=config.MESSAGE_RETENTION_PERIOD)`

template.yml
`MessageRetentionPeriod:
      Description: 'The number of seconds that Amazon SQS retains a message. You can
        specify an integer value from 60 seconds (1 minute) to 1209600 seconds (14 days). This is used in the backoff calculation.'`

**Comment by AlexPinhel** [comment]
The retention period is from 1 min to 14 days as described here in the documentation. https://aws.amazon.com/sqs/faqs/
You can search for retention.
The delay queues which is another feature is limited to 15 mins indeed.

**Comment by edank** [comment]
apologies if I'm not understanding it, but in replay.py, the ExpoBackoffFullJitter call sends in the retention period (< 14days) as the argument for the delay cap which is used for the message delay (< 15m). 

Am I missing something?
