### ISSUE TITLE
Error on Send Message [DelaySeconds Parameter]

### ISSUE THREAD

**Issue by pizzo90** [aws-samples/amazon-sqs-dlq-replay-backoff#8]
```[ERROR] ClientError: An error occurred (InvalidParameterValue) when calling the SendMessage operation: Value 54524 for parameter DelaySeconds is invalid. Reason: DelaySeconds must be >= 0 and <= 900. Traceback (most recent call last):   File "/var/task/replay.py", line 57, in handler     MessageAttributes=record['messageAttributes']   File "/var/task/botocore/client.py", line 395, in _api_call     return self._make_api_call(operation_name, kwargs)   File "/var/task/botocore/client.py", line 725, in _make_api_call     raise error_class(parsed_response, operation_name)```

Lambda ENV Configuration:
```
BACKOFF_RATE = 100
MESSAGE_RETENTION_PERIOD = 1209600
MAX_ATTEMPS = 200
LOG_LEVEL = DEBUG
SQS_MAIN_URL = https://sqs.eu-central-1.amazonaws.com/*******
```
I've experincing issues with this lambda function, sometimes [very often] the DelaySeconds parameter go higher than the maximum supported by SQS.
Looking into the codebase I cannot see nothing about some cap (900 seconds) in delaySeconds parameter when the replay function put back the message in the main queue.
It is what about configuration (ENV), SQS configuration or this is an known issue?

Thanks,
Andrea.

**Comment by AlexPinhel** [comment]
Let me look at it in the next days and will come back to you.

**Comment by AlexPinhel** [comment]
The file replay.py has been updated with a verification of the delay seconds parameter for SQS.
